# Generated by Django 4.0.4 on 2022-05-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(default='Monday', max_length=10)),
                ('sixam', models.CharField(default='Workout', max_length=200)),
                ('sevenam', models.CharField(default='Breakfast', max_length=200)),
                ('eightam', models.CharField(max_length=200)),
                ('nineam', models.CharField(max_length=200)),
                ('tenam', models.CharField(max_length=200)),
                ('elevenam', models.CharField(max_length=200)),
                ('twelveam', models.CharField(max_length=200)),
                ('onepm', models.CharField(default='Lunch', max_length=200)),
                ('twopm', models.CharField(max_length=200)),
                ('threepm', models.CharField(max_length=200)),
                ('fourpm', models.CharField(max_length=200)),
                ('fivepm', models.CharField(default='Break', max_length=200)),
                ('sixpm', models.CharField(max_length=200)),
                ('sevenpm', models.CharField(max_length=200)),
                ('eightpm', models.CharField(max_length=200)),
                ('ninepm', models.CharField(default='Dinner', max_length=200)),
                ('tenpm', models.CharField(default='Application process', max_length=200)),
                ('elevenpm', models.CharField(default='Day Review', max_length=200)),
                ('twelvepm', models.CharField(default='Sleep', max_length=200)),
            ],
        ),
    ]
