# Generated by Django 4.0.4 on 2022-05-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='day',
            field=models.CharField(default='Thursday', max_length=10),
        ),
        migrations.AlterField(
            model_name='routine',
            name='eightam',
            field=models.CharField(default='interview questions', max_length=200),
        ),
        migrations.AlterField(
            model_name='routine',
            name='eightpm',
            field=models.CharField(default='self skill ++', max_length=200),
        ),
        migrations.AlterField(
            model_name='routine',
            name='elevenam',
            field=models.CharField(default='data structures', max_length=200),
        ),
        migrations.AlterField(
            model_name='routine',
            name='fourpm',
            field=models.CharField(default='internship', max_length=200),
        ),
        migrations.AlterField(
            model_name='routine',
            name='nineam',
            field=models.CharField(default='interview questions', max_length=200),
        ),
        migrations.AlterField(
            model_name='routine',
            name='sevenpm',
            field=models.CharField(default='self skill ++', max_length=200),
        ),
        migrations.AlterField(
            model_name='routine',
            name='sixpm',
            field=models.CharField(default='self skill ++', max_length=200),
        ),
        migrations.AlterField(
            model_name='routine',
            name='tenam',
            field=models.CharField(default='Aptitude', max_length=200),
        ),
        migrations.AlterField(
            model_name='routine',
            name='threepm',
            field=models.CharField(default='internship', max_length=200),
        ),
        migrations.AlterField(
            model_name='routine',
            name='twelveam',
            field=models.CharField(default='algorithms', max_length=200),
        ),
        migrations.AlterField(
            model_name='routine',
            name='twopm',
            field=models.CharField(default='internship', max_length=200),
        ),
    ]
