# Generated by Django 4.0.4 on 2022-05-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0002_alter_routine_day_alter_routine_eightam_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='day',
            field=models.CharField(default='Saturday', max_length=10),
        ),
    ]
