# Generated by Django 4.0.4 on 2022-06-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('client', models.CharField(blank=True, max_length=50, null=True)),
                ('key_feature_1', models.CharField(blank=True, max_length=20)),
                ('key_feature_2', models.CharField(blank=True, max_length=20)),
                ('key_feature_3', models.CharField(blank=True, max_length=20)),
                ('key_feature_4', models.CharField(blank=True, max_length=20)),
                ('key_feature_5', models.CharField(blank=True, max_length=20)),
                ('key_feature_6', models.CharField(blank=True, max_length=20)),
                ('tech_stack_1', models.CharField(blank=True, max_length=20)),
                ('tech_stack_2', models.CharField(blank=True, max_length=20)),
                ('tech_stack_3', models.CharField(blank=True, max_length=20)),
                ('tech_stack_4', models.CharField(blank=True, max_length=20)),
                ('tech_stack_5', models.CharField(blank=True, max_length=20)),
                ('tech_stack_6', models.CharField(blank=True, max_length=20)),
                ('github', models.CharField(blank=True, max_length=100)),
                ('deployed', models.CharField(blank=True, max_length=100)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
