# Generated by Django 4.0.4 on 2022-06-01 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='color_id',
            field=models.IntegerField(default=6),
        ),
    ]
