# Generated by Django 4.0.4 on 2022-06-01 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_color_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='color_id',
            field=models.IntegerField(default=3),
        ),
    ]
