# Generated by Django 4.0.4 on 2022-06-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_color_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_1',
            field=models.ImageField(blank=True, upload_to='projectphotos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='project',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='projectphotos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='project',
            name='image_3',
            field=models.ImageField(blank=True, upload_to='projectphotos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='color_id',
            field=models.IntegerField(default=6),
        ),
    ]
