# Generated by Django 4.0.4 on 2022-06-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_image_1_project_image_2_project_image_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='color_id',
            field=models.IntegerField(default=3),
        ),
    ]
