# Generated by Django 4.0.4 on 2022-06-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='photo_1',
            field=models.ImageField(blank=True, upload_to='blogphotos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='photo_main',
            field=models.ImageField(blank=True, upload_to='blogphotos/%Y/%m/%d/'),
        ),
    ]
