# Generated by Django 4.0.4 on 2022-06-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='image_profile',
            field=models.ImageField(blank=True, upload_to='profilephotos/%Y/%m/%d/'),
        ),
    ]
